linters-settings:
  depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax # allow unless explicitly denied
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
          deny:
            - pkg: io/ioutil
              desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goheader:
    values:
      const:
        - LICENSE: BSD-3-Clause
    template: |-
      SPDX-License-Identifier: {{ LICENSE }}
  goconst:
    min-len: 2
    min-occurrences: 5
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - deprecatedComment
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 30
  goimports:
    local-prefixes: github.com/stmcginnis
  govet:
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # don't enable:
  # - asciicheck
  # - exhaustive
  # - gochecknoinits
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - lll
  # - nestif
  # - prealloc
  # - testpackage
  # - revive
  # - scopelint
  # - wsl

issues:
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
    - "G402: TLS InsecureSkipVerify may be true"
    - "`(F|f)ibre` is a misspelling"
    - "`(C|c)ancell.*` is a misspelling"
  exclude-dirs:
    - examples
    - tools
